x-common-environment: &mongo-environment
  MONGO_URI: mongodb://root:example@coinbase_mongodb:27017/?authSource=admin

services:
    mongo:
        build:
            context: ./database
        container_name: coinbase_mongo
        hostname: coinbase_mongodb
        environment:
            MONGO_INITDB_DATABASE: coinbase
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
        command: mongod --quiet --bind_ip 0.0.0.0 --logpath /dev/null
        networks:
            - coinbase_network
    socket:
        container_name: coinbase_websocket
        build:
            context: ./socket
        command: python3 main.py
        depends_on:
            - mongo
        networks:
            - coinbase_network
        environment:
          <<: *mongo-environment
    api:
        container_name: coinbase_api
        ports:
            - 8000:8000
        build:
            context: ./backend
        command: fastapi run main.py --port 8000
        depends_on:
            - mongo
            - socket
        networks:
          - coinbase_network
    frontend:
      container_name: react
      ports:
        - 3000:3000
      build:
        context: ./frontend
      command: serve -s -l 3000 ./build
volumes:
    mongodb_data:
networks:
    coinbase_network:
        driver: bridge